name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Capacitor CLI
        run: |
          npm init -y
          npm install @capacitor/cli @capacitor/core @capacitor/android
          mkdir -p www
          printf '<!doctype html><title>Loading…</title>' > www/index.html

      - name: Init Capacitor project (points to your site URL)
        run: |
          npx cap init "ClinicBot" com.clinicbot.app --web-dir=www
          cat > capacitor.config.json << 'JSON'
          {
            "appId": "com.clinicbot.app",
            "appName": "ClinicBot",
            "webDir": "www",
            "server": {
              "url": "https://clinicbot.github.io/larosh/",
              "cleartext": false
            }
          }
          JSON

      - name: Add Android platform
        run: npx cap add android
      - name: Make app icon from appl.png
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          ICON=appl.png
          # וידוא שהקובץ קיים
          test -f "$ICON"
          # גדלים לפי צפיפויות
          convert "$ICON" -resize 48x48  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          convert "$ICON" -resize 72x72  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          convert "$ICON" -resize 96x96  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          convert "$ICON" -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          convert "$ICON" -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
          # אייקון עגול (למכשירים שמציגים עגול)
          convert "$ICON" -resize 48x48  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
          convert "$ICON" -resize 72x72  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
          convert "$ICON" -resize 96x96  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
          convert "$ICON" -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
          convert "$ICON" -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png

      - name: Bump compile/target SDK to 35
        run: |
          sed -i 's/compileSdkVersion = 34/compileSdkVersion = 35/' android/variables.gradle || true
          sed -i 's/targetSdkVersion = 34/targetSdkVersion = 35/' android/variables.gradle || true

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android API 35 packages
        run: |
          yes | sdkmanager "platforms;android-35" "build-tools;35.0.0" "platform-tools"

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClinicBot-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Decode keystore from secrets
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/derma_keystore.jks
          {
            echo "MY_STORE_FILE=derma_keystore.jks"
            echo "MY_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
            echo "MY_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}"
            echo "MY_KEY_PASSWORD=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}"
          } >> android/gradle.properties

      - name: Configure release signing in Gradle
        run: |
          APP_GRADLE=android/app/build.gradle
          # הוסף signingConfigs אם לא קיים
          if ! grep -q "signingConfigs {" "$APP_GRADLE"; then
            awk '{
              print $0
              if ($0 ~ /android \{/) {
                print "    signingConfigs {"
                print "        release {"
                print "            storeFile file(MY_STORE_FILE)"
                print "            storePassword MY_STORE_PASSWORD"
                print "            keyAlias MY_KEY_ALIAS"
                print "            keyPassword MY_KEY_PASSWORD"
                print "        }"
                print "    }"
              }
            }' "$APP_GRADLE" > "$APP_GRADLE.tmp" && mv "$APP_GRADLE.tmp" "$APP_GRADLE"
          fi
          # חבר את buildTypes.release לחתימה + אופטימיזציה
          if ! grep -q "signingConfig signingConfigs.release" "$APP_GRADLE"; then
            sed -i 's/release {/release {\n            minifyEnabled true\n            shrinkResources true\n            signingConfig signingConfigs.release/' "$APP_GRADLE"
          fi

      - name: Build Release (APK + AAB)
        run: |
          cd android
          ./gradlew assembleRelease bundleRelease --no-daemon

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DermaMatch-release
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/bundle/release/app-release.aab
