name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Capacitor CLI
        run: |
          npm init -y
          npm install @capacitor/cli @capacitor/core @capacitor/android

      - name: Init Capacitor project (points to your site URL)
        run: https://clinicbot.github.io/larosh/|
          npx cap init "ClinicBot" com.clinicbot.app --web-dir=.
          cat > capacitor.config.json << 'JSON'
          {
            "appId": "com.clinicbot.app",
            "appName": "ClinicBot",
            "webDir": ".",
            "server": {
              "url": "https://clinicbot.github.io/larosh/",
              "cleartext": false
            }
          }
          JSON

      - name: Add Android platform
        run: npx cap add android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK (debug)
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClinicBot-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
